#!/bin/bash
#https://cupermind.com/post/Ansible-Virtualenv/

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
VENV="$PROJECT_ROOT/.venv"

if [ ! -e "$VENV" ]; then
    virtualenv $VENV
    source $VENV/bin/activate
    pip install -r $PROJECT_ROOT/requirements.txt
    if [ $? -ne 0 ]; then
        rm -rf $VENV
        exit 1
    fi
fi

if [ ! -z "$1" ]; then
    source $VENV/bin/activate
    $VENV/bin/ansible-playbook $*
fi
